#!/usr/bin/env bash
set -u

PUBLIC_BASE="${PUBLIC_BASE:-https://foresakenly-figgiest-jazmin.ngrok-free.dev}"
CW_OAUTH_BASE_URL="${CW_OAUTH_BASE_URL:-}"

ENTRY_FRONTEND_HOST="${ENTRY_FRONTEND_HOST:-0.0.0.0}"
ENTRY_FRONTEND_PORT="${ENTRY_FRONTEND_PORT:-8512}"

SMALL_CLAIMS_HOST="${SMALL_CLAIMS_HOST:-0.0.0.0}"
SMALL_CLAIMS_PORT="${SMALL_CLAIMS_PORT:-8513}"

CHARGE_BACK_HOST="${CHARGE_BACK_HOST:-0.0.0.0}"
CHARGE_BACK_PORT="${CHARGE_BACK_PORT:-8514}"

CW_REGULATORY_HOST="${CW_REGULATORY_HOST:-0.0.0.0}"
CW_REGULATORY_PORT="${CW_REGULATORY_PORT:-8515}"

TWILIO_HOST="${TWILIO_HOST:-0.0.0.0}"
TWILIO_PORT="${TWILIO_PORT:-5000}"

OAUTH_HOST="${OAUTH_HOST:-127.0.0.1}"
OAUTH_PORT="${OAUTH_PORT:-8510}"

STREAMLIT_HOST="${STREAMLIT_HOST:-127.0.0.1}"
STREAMLIT_PORT="${STREAMLIT_PORT:-8509}"

APP_DIR="${APP_DIR:-/home/ec2-user/phone_call1}"
CHARGE_BACK_SCRIPT="${CHARGE_BACK_SCRIPT:-charge_back_initiator.py}"
CW_REGULATORY_SCRIPT="${CW_REGULATORY_SCRIPT:-cw_regulatory_complaint_sender.py}"
PID_DIR="$APP_DIR/pids"
LOG_DIR="$APP_DIR/logs"

NGROK_TARGET="${NGROK_TARGET:-http://localhost:80}"
NGROK_DOMAIN="${NGROK_DOMAIN:-foresakenly-figgiest-jazmin.ngrok-free.dev}"

# Nginx routing file generated by this script.
# It makes the public subpaths reach the corresponding Streamlit ports.
NGINX_ROUTE_CONFIG="${NGINX_ROUTE_CONFIG:-/etc/nginx/conf.d/complaint_warrior_apps.conf}"
INSTALL_NGINX_ROUTES="${INSTALL_NGINX_ROUTES:-1}"

if [[ -z "$PUBLIC_BASE" && -n "$CW_OAUTH_BASE_URL" ]]; then
  PUBLIC_BASE="$CW_OAUTH_BASE_URL"
fi
PUBLIC_BASE="${PUBLIC_BASE%/}"

mkdir -p "$PID_DIR" "$LOG_DIR"

ts() {
  date '+[%Y-%m-%d %H:%M:%S]'
}

log() {
  echo "$(ts) $*"
}

is_running_pid() {
  local pid="$1"
  [[ -n "${pid:-}" ]] && kill -0 "$pid" 2>/dev/null
}

read_pid() {
  local file="$1"
  [[ -f "$file" ]] && cat "$file" 2>/dev/null || true
}

stop_pidfile() {
  local name="$1"
  local pidfile="$2"
  local pid
  pid="$(read_pid "$pidfile")"

  if [[ -n "$pid" ]] && is_running_pid "$pid"; then
    log "Stopping $name PID $pid from $pidfile"
    kill "$pid" 2>/dev/null || true
    sleep 1
    if is_running_pid "$pid"; then
      kill -9 "$pid" 2>/dev/null || true
    fi
  fi
  rm -f "$pidfile"
}

stop_pattern() {
  local label="$1"
  local pattern="$2"
  local pids

  pids="$(pgrep -f "$pattern" || true)"
  if [[ -n "$pids" ]]; then
    log "Stopping by pattern: $label (pids: $pids)"
    pkill -f "$pattern" 2>/dev/null || true
    sleep 1
    pkill -9 -f "$pattern" 2>/dev/null || true
  fi
}

stop_all() {
  log "Stopping all..."

  stop_pidfile "ngrok" "$PID_DIR/ngrok.pid"
  stop_pidfile "small_claims" "$PID_DIR/small_claims.pid"
  stop_pidfile "charge_back" "$PID_DIR/charge_back.pid"
  stop_pidfile "cw_regulatory" "$PID_DIR/cw_regulatory.pid"
  stop_pidfile "entry_frontend" "$PID_DIR/entry_frontend.pid"
  stop_pidfile "streamlit" "$PID_DIR/streamlit.pid"
  stop_pidfile "oauth" "$PID_DIR/oauth.pid"
  stop_pidfile "twilio" "$PID_DIR/twilio.pid"

  stop_pattern "twilio app" "python3 $APP_DIR/app.py"
  stop_pattern "oauth server" "python3 $APP_DIR/gmail_oauth_server.py"
  stop_pattern "Complaint Warrior" "streamlit run $APP_DIR/cw_app_phone.py"
  stop_pattern "Complaint Warrior" "python3 -m streamlit run $APP_DIR/cw_app_phone.py"
  stop_pattern "entry frontend" "streamlit run $APP_DIR/entry_frontend.py"
  stop_pattern "entry frontend" "python3 -m streamlit run $APP_DIR/entry_frontend.py"
  stop_pattern "Small Claim Court Warrior" "streamlit run $APP_DIR/small_claim_court_warrior.py"
  stop_pattern "Small Claim Court Warrior" "python3 -m streamlit run $APP_DIR/small_claim_court_warrior.py"
  stop_pattern "Charge-back Initiator" "streamlit run $APP_DIR/$CHARGE_BACK_SCRIPT"
  stop_pattern "Charge-back Initiator" "python3 -m streamlit run $APP_DIR/$CHARGE_BACK_SCRIPT"
  stop_pattern "CW Regulatory" "streamlit run $APP_DIR/$CW_REGULATORY_SCRIPT"
  stop_pattern "CW Regulatory" "python3 -m streamlit run $APP_DIR/$CW_REGULATORY_SCRIPT"
  stop_pattern "ngrok" "ngrok http"

  log "Done."
}

write_nginx_routes() {
  if [[ "$INSTALL_NGINX_ROUTES" != "1" ]]; then
    log "Skipping nginx route installation because INSTALL_NGINX_ROUTES=$INSTALL_NGINX_ROUTES"
    return 0
  fi

  log "Writing nginx routes to $NGINX_ROUTE_CONFIG"

  local tmp
  tmp="$(mktemp)"
  cat >"$tmp" <<EOF
# Generated by $(basename "$0").
# Public host: $NGROK_DOMAIN

map \$http_upgrade \$connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    listen [::]:80;
    server_name $NGROK_DOMAIN;

    client_max_body_size 50m;

    # Gmail OAuth callback server.
    location = /auth/start {
        proxy_pass http://127.0.0.1:$OAUTH_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location = /auth/status {
        proxy_pass http://127.0.0.1:$OAUTH_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location = /oauth2callback {
        proxy_pass http://127.0.0.1:$OAUTH_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Twilio webhook endpoints.
    location ~ ^/(health|voice_human|voice_machine|status|transcription|recording_done)$ {
        proxy_pass http://127.0.0.1:$TWILIO_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Normalize app paths to trailing-slash versions.
    location = /complaint_warrior { return 301 /complaint_warrior/; }
    location = /small_claim_court_warrior { return 301 /small_claim_court_warrior/; }
    location = /charge_back_initiator { return 301 /charge_back_initiator/; }
    location = /cw_regulatory { return 301 /cw_regulatory/; }

    # Main Complaint Warrior Streamlit app.
    location ^~ /complaint_warrior/ {
        proxy_pass http://127.0.0.1:$STREAMLIT_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 86400;
        proxy_buffering off;
    }

    # Small Claim Court Warrior.
    location ^~ /small_claim_court_warrior/ {
        proxy_pass http://127.0.0.1:$SMALL_CLAIMS_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 86400;
        proxy_buffering off;
    }

    # Charge-back Initiator.
    location ^~ /charge_back_initiator/ {
        proxy_pass http://127.0.0.1:$CHARGE_BACK_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 86400;
        proxy_buffering off;
    }

    # Regulatory Complaint Sender.
    location ^~ /cw_regulatory/ {
        proxy_pass http://127.0.0.1:$CW_REGULATORY_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 86400;
        proxy_buffering off;
    }

    # Entry/chooser app remains the default root application.
    location / {
        proxy_pass http://127.0.0.1:$ENTRY_FRONTEND_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 86400;
        proxy_buffering off;
    }
}
EOF

  sudo mkdir -p "$(dirname "$NGINX_ROUTE_CONFIG")"
  sudo cp "$tmp" "$NGINX_ROUTE_CONFIG"
  rm -f "$tmp"

  if ! sudo nginx -t; then
    log "nginx configuration test failed. The generated file is: $NGINX_ROUTE_CONFIG"
    log "Check for another server block using the same server_name: $NGROK_DOMAIN"
    return 1
  fi
}

start_nginx() {
  write_nginx_routes || return 1
  log "Starting/reloading nginx..."
  sudo systemctl enable nginx >/dev/null 2>&1 || true
  sudo systemctl restart nginx
  sudo systemctl status nginx --no-pager || true
}

start_twilio() {
  log "Starting Twilio webhook server: app.py on ${TWILIO_HOST}:${TWILIO_PORT}"
  cd "$APP_DIR" || exit 1

  nohup python3 "$APP_DIR/app.py" >>"$LOG_DIR/twilio.log" 2>&1 &
  local pid=$!
  echo "$pid" > "$PID_DIR/twilio.pid"
  sleep 2

  if is_running_pid "$pid"; then
    log "Twilio webhook pid=$pid. Log: $LOG_DIR/twilio.log"
  else
    log "Twilio failed to stay up. Check: $LOG_DIR/twilio.log"
  fi
}

start_oauth() {
  log "Starting OAuth server: gmail_oauth_server.py on ${OAUTH_HOST}:${OAUTH_PORT}"
  cd "$APP_DIR" || exit 1

  export PUBLIC_BASE="$PUBLIC_BASE"

  nohup python3 "$APP_DIR/gmail_oauth_server.py" >>"$LOG_DIR/oauth.log" 2>&1 &
  local pid=$!
  echo "$pid" > "$PID_DIR/oauth.pid"
  sleep 3

  if ss -ltnp 2>/dev/null | grep -q "${OAUTH_HOST}:${OAUTH_PORT}"; then
    log "OAuth is listening on ${OAUTH_HOST}:${OAUTH_PORT}. Log: $LOG_DIR/oauth.log"
  else
    log "OAuth failed to bind ${OAUTH_HOST}:${OAUTH_PORT}. Check: $LOG_DIR/oauth.log"
  fi
}

start_complaint_warrior() {
  log "Starting Complaint Warrior: cw_app_phone.py on ${STREAMLIT_HOST}:${STREAMLIT_PORT}"
  cd "$APP_DIR" || exit 1

  nohup python3 -m streamlit run "$APP_DIR/cw_app_phone.py" \
    --server.address "$STREAMLIT_HOST" \
    --server.port "$STREAMLIT_PORT" \
    --server.baseUrlPath complaint_warrior \
    >>"$LOG_DIR/streamlit.log" 2>&1 &
  local pid=$!
  echo "$pid" > "$PID_DIR/streamlit.pid"
  sleep 3

  if is_running_pid "$pid"; then
    log "Complaint Warrior pid=$pid. Log: $LOG_DIR/streamlit.log"
  else
    log "Complaint Warrior failed to stay up. Check: $LOG_DIR/streamlit.log"
  fi
}

start_small_claims() {
  log "Starting Small Claim Court Warrior: small_claim_court_warrior.py on ${SMALL_CLAIMS_HOST}:${SMALL_CLAIMS_PORT}"
  cd "$APP_DIR" || exit 1

  nohup python3 -m streamlit run "$APP_DIR/small_claim_court_warrior.py" \
    --server.address "$SMALL_CLAIMS_HOST" \
    --server.port "$SMALL_CLAIMS_PORT" \
    --server.baseUrlPath small_claim_court_warrior \
    >>"$LOG_DIR/small_claims.log" 2>&1 &
  local pid=$!
  echo "$pid" > "$PID_DIR/small_claims.pid"
  sleep 3

  if is_running_pid "$pid"; then
    log "Small Claim Court Warrior pid=$pid. Log: $LOG_DIR/small_claims.log"
  else
    log "Small Claim Court Warrior failed to stay up. Check: $LOG_DIR/small_claims.log"
  fi
}


start_charge_back() {
  log "Starting Charge-back Initiator: ${CHARGE_BACK_SCRIPT} on ${CHARGE_BACK_HOST}:${CHARGE_BACK_PORT}"
  cd "$APP_DIR" || exit 1

  if [[ ! -f "$APP_DIR/$CHARGE_BACK_SCRIPT" ]]; then
    log "Charge-back Initiator script not found: $APP_DIR/$CHARGE_BACK_SCRIPT"
    return 0
  fi

  nohup python3 -m streamlit run "$APP_DIR/$CHARGE_BACK_SCRIPT" \
    --server.address "$CHARGE_BACK_HOST" \
    --server.port "$CHARGE_BACK_PORT" \
    --server.baseUrlPath charge_back_initiator \
    >>"$LOG_DIR/charge_back.log" 2>&1 &
  local pid=$!
  echo "$pid" > "$PID_DIR/charge_back.pid"
  sleep 3

  if is_running_pid "$pid"; then
    log "Charge-back Initiator pid=$pid. Log: $LOG_DIR/charge_back.log"
  else
    log "Charge-back Initiator failed to stay up. Check: $LOG_DIR/charge_back.log"
  fi
}

start_cw_regulatory() {
  log "Starting CW Regulatory Complaint Sender: ${CW_REGULATORY_SCRIPT} on ${CW_REGULATORY_HOST}:${CW_REGULATORY_PORT}"
  cd "$APP_DIR" || exit 1

  if [[ ! -f "$APP_DIR/$CW_REGULATORY_SCRIPT" ]]; then
    log "CW Regulatory script not found: $APP_DIR/$CW_REGULATORY_SCRIPT"
    return 0
  fi

  nohup python3 -m streamlit run "$APP_DIR/$CW_REGULATORY_SCRIPT" \
    --server.address "$CW_REGULATORY_HOST" \
    --server.port "$CW_REGULATORY_PORT" \
    --server.baseUrlPath cw_regulatory \
    >>"$LOG_DIR/cw_regulatory.log" 2>&1 &
  local pid=$!
  echo "$pid" > "$PID_DIR/cw_regulatory.pid"
  sleep 3

  if is_running_pid "$pid"; then
    log "CW Regulatory pid=$pid. Log: $LOG_DIR/cw_regulatory.log"
  else
    log "CW Regulatory failed to stay up. Check: $LOG_DIR/cw_regulatory.log"
  fi
}

start_entry_frontend() {
  log "Starting entry frontend: entry_frontend.py on ${ENTRY_FRONTEND_HOST}:${ENTRY_FRONTEND_PORT}"
  cd "$APP_DIR" || exit 1

  export CW_PUBLIC_BASE_URL="$PUBLIC_BASE"
  export CW_CUSTOMER_APP_URL="${CW_CUSTOMER_APP_URL:-${PUBLIC_BASE}/complaint_warrior}"
  export CW_COMPANY_APP_URL="${CW_COMPANY_APP_URL:-${PUBLIC_BASE}/complaint_warrior}"
  export CW_SMALL_CLAIMS_APP_URL="${CW_SMALL_CLAIMS_APP_URL:-${PUBLIC_BASE}/small_claim_court_warrior}"
  export CW_CHARGE_BACK_APP_URL="${CW_CHARGE_BACK_APP_URL:-${PUBLIC_BASE}/charge_back_initiator}"
  export CW_REGULATORY_APP_URL="${CW_REGULATORY_APP_URL:-${PUBLIC_BASE}/cw_regulatory}"
  export CW_FB_POSTER_DOWNLOAD_URL="${CW_FB_POSTER_DOWNLOAD_URL:-${PUBLIC_BASE}/downloads/fb-poster/}"

  nohup python3 -m streamlit run "$APP_DIR/entry_frontend.py" \
    --server.address "$ENTRY_FRONTEND_HOST" \
    --server.port "$ENTRY_FRONTEND_PORT" \
    >>"$LOG_DIR/entry_frontend.log" 2>&1 &
  local pid=$!
  echo "$pid" > "$PID_DIR/entry_frontend.pid"
  sleep 3

  if is_running_pid "$pid"; then
    log "Entry frontend pid=$pid. Log: $LOG_DIR/entry_frontend.log"
    log "Chooser routes: / -> entry_frontend, /complaint_warrior -> cw_app_phone, /small_claim_court_warrior -> small_claim_court_warrior, /charge_back_initiator -> charge_back_initiator, /cw_regulatory -> cw_regulatory_complaint_sender, /downloads/fb-poster/ -> desktop download"
  else
    log "Entry frontend failed to stay up. Check: $LOG_DIR/entry_frontend.log"
  fi
}

start_ngrok() {
  log "Starting ngrok -> $NGROK_TARGET"
  cd "$APP_DIR" || exit 1

  nohup ngrok http --domain="$NGROK_DOMAIN" 80 >>"$LOG_DIR/ngrok.log" 2>&1 &
  local pid=$!
  echo "$pid" > "$PID_DIR/ngrok.pid"
  sleep 3

  if is_running_pid "$pid"; then
    log "ngrok pid=$pid. Log: $LOG_DIR/ngrok.log"
  else
    log "ngrok failed to stay up. Check: $LOG_DIR/ngrok.log"
  fi
}

status_all() {
  log "=== STATUS ==="

  if systemctl is-active --quiet nginx; then
    log "nginx: active"
  else
    log "nginx: inactive"
  fi

  for svc in twilio oauth streamlit entry_frontend small_claims charge_back cw_regulatory ngrok; do
    pidfile="$PID_DIR/$svc.pid"
    pid="$(read_pid "$pidfile")"
    if [[ -n "$pid" ]] && is_running_pid "$pid"; then
      log "$svc: RUNNING (pid $pid)"
    else
      log "$svc: NOT running"
    fi
  done

  log "Listening ports (best-effort):"
  ss -ltnp 2>/dev/null | grep -E ':80 |:5000 |:8509 |:8510 |:8512 |:8513 |:8514 |:8515 ' || true
  log "Nginx route config: $NGINX_ROUTE_CONFIG"
  if [[ -f "$NGINX_ROUTE_CONFIG" ]]; then
    log "nginx route file exists"
  else
    log "nginx route file is missing"
  fi
  log "PUBLIC_BASE=$PUBLIC_BASE"
  log "CW_CUSTOMER_APP_URL=${CW_CUSTOMER_APP_URL:-${PUBLIC_BASE}/complaint_warrior}"
  log "CW_COMPANY_APP_URL=${CW_COMPANY_APP_URL:-${PUBLIC_BASE}/complaint_warrior}"
  log "CW_SMALL_CLAIMS_APP_URL=${CW_SMALL_CLAIMS_APP_URL:-${PUBLIC_BASE}/small_claim_court_warrior}"
  log "CW_CHARGE_BACK_APP_URL=${CW_CHARGE_BACK_APP_URL:-${PUBLIC_BASE}/charge_back_initiator}"
  log "CW_REGULATORY_APP_URL=${CW_REGULATORY_APP_URL:-${PUBLIC_BASE}/cw_regulatory}"
  log "CW_FB_POSTER_DOWNLOAD_URL=${CW_FB_POSTER_DOWNLOAD_URL:-${PUBLIC_BASE}/downloads/fb-poster/}"
}

start_stack() {
  log "Starting stack in $APP_DIR"
  start_nginx
  start_twilio
  start_oauth
  start_complaint_warrior
  start_small_claims
  start_charge_back
  start_cw_regulatory
  start_ngrok
  start_entry_frontend
  status_all
}

case "${1:-start}" in
  stop)
    stop_all
    ;;
  restart)
    stop_all
    start_stack
    ;;
  start)
    stop_all
    start_stack
    ;;
  status)
    status_all
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac
