# -*- coding: utf-8 -*-
"""
Complaint Warrior: Regulatory Complaint Sender

Streamlit app that:
  1. Reads complaints from a SQLite database, including the Complaint Warrior cw_store.sqlite format.
  2. Uses the OpenAI ChatGPT API to recommend organizations/agencies to contact.
  3. Drafts individualized complaint letters.
  4. Lets the user review/edit recipients and letters.
  5. Sends selected letters through the user's Gmail account using the Gmail API.
  6. Logs all outreach back into SQLite.

Important safety design:
  - The app never sends automatically after GPT generation.
  - The user must check a confirmation box and click Send.
  - BBB/FTC/AG/FDACS are often web-form based. The app prepares text for web forms;
    it sends email only when a verified recipient email is supplied.
  - GPT is instructed not to invent email addresses. Always verify recipient emails.

Run:
  pip install -r requirements_cw_sender.txt
  streamlit run cw_escalation_desk.py

Local-file assumptions:
  - config.ini is in the same directory as this app.
  - config.ini contains [OpenAI] api_key = ...
  - cw_store.sqlite is in the same directory.
  - Gmail files are in the same directory: credentials.json and either
    cw_gmail_tokens.sqlite from gmail_oauth_server.py or gmail_token.json
    generated by this app's local OAuth flow.
"""

from __future__ import annotations

import base64
import configparser
import json
import mimetypes
import os
import pickle
import re
import sqlite3
import time
from dataclasses import dataclass, asdict
from datetime import datetime
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email import encoders
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
import streamlit as st

# Optional dependencies are imported lazily where possible to make the UI load even
# before OAuth/OpenAI packages are configured.
try:
    from openai import OpenAI
except Exception:  # pragma: no cover
    OpenAI = None

try:
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request
    from google_auth_oauthlib.flow import InstalledAppFlow
    from googleapiclient.discovery import build
    from google.auth.exceptions import RefreshError
except Exception:  # pragma: no cover
    Credentials = None
    Request = None
    InstalledAppFlow = None
    build = None
    RefreshError = Exception

APP_TITLE = "Complaint Warrior — Escalation Desk"
APP_DIR = Path(__file__).resolve().parent
CONFIG_PATH = APP_DIR / "config.ini"


def _load_config() -> configparser.ConfigParser:
    cfg = configparser.ConfigParser()
    if CONFIG_PATH.exists():
        cfg.read(CONFIG_PATH, encoding="utf-8")
    return cfg


CFG = _load_config()


def cfg_get(section: str, option: str, default: str = "") -> str:
    """Case-insensitive config lookup with safe fallback."""
    for sec in CFG.sections():
        if sec.lower() == section.lower() and CFG.has_option(sec, option):
            return CFG.get(sec, option).strip()
    return default


def local_path(value: str) -> str:
    """Resolve config paths relative to the current app directory."""
    value = (value or "").strip()
    if not value:
        return ""
    p = Path(value)
    return str(p if p.is_absolute() else APP_DIR / p)


def get_openai_api_key() -> str:
    # Primary: config.ini [OpenAI] api_key = ...
    key = cfg_get("OpenAI", "api_key", "")
    # Optional fallback for existing deployments.
    return key or os.environ.get("OPENAI_API_KEY", "").strip()


DEFAULT_DB_PATH = local_path(cfg_get("Database", "path", "cw_store.sqlite"))
OPENAI_MODEL = cfg_get("OpenAI", "model", os.environ.get("OPENAI_MODEL", "gpt-4o-mini"))
GMAIL_CLIENT_SECRETS = local_path(cfg_get("Gmail", "credentials_file", "credentials.json"))
GMAIL_TOKEN_FILE = local_path(cfg_get("Gmail", "token_file", "gmail_token.json"))
GMAIL_TOKEN_DB = local_path(cfg_get("Gmail", "token_db", "cw_gmail_tokens.sqlite"))
GMAIL_TOKEN_KEY = cfg_get("Gmail", "token_key", "default")
# Legacy fallback used by auth_gmail.py. Kept to reuse existing working Gmail auth.
GMAIL_TOKEN_PICKLE = local_path(cfg_get("Gmail", "token_pickle", "token.pickle"))
OUTREACH_TABLE = "regulatory_outreach"
SCOPES = ["https://www.googleapis.com/auth/gmail.send"]


def get_current_app_user_email() -> str:
    """Return the Complaint Warrior app user whose complaints should be shown.

    Because this regulatory module runs as a separate Streamlit app, it cannot
    read cw_app_phone.py's Streamlit session directly. Set one of these in the
    start script or config.ini to keep all modules on the same user:
      export CW_APP_USER_EMAIL=customer@example.com
      [User] email = customer@example.com
      [AppUser] email = customer@example.com
      [ComplaintWarrior] user_email = customer@example.com
    """
    candidates = [
        os.environ.get("CW_APP_USER_EMAIL", ""),
        os.environ.get("APP_USER_EMAIL", ""),
        cfg_get("User", "email", ""),
        cfg_get("AppUser", "email", ""),
        cfg_get("ComplaintWarrior", "user_email", ""),
    ]
    for value in candidates:
        value = clean_text(value).lower() if "clean_text" in globals() else str(value or "").strip().lower()
        if value:
            return value
    return ""


def filter_records_for_current_user(records: List["ComplaintRecord"]) -> List["ComplaintRecord"]:
    current_user = get_current_app_user_email()
    if not current_user:
        return records
    return [r for r in records if (r.user_email or "").strip().lower() == current_user]


# -----------------------------------------------------------------------------
# Organization registry
# -----------------------------------------------------------------------------
# Keep emails empty unless you have verified a current, correct mailbox.
# Web-only agencies should be handled by preparing text for copy/paste.
DEFAULT_ORG_REGISTRY: List[Dict[str, str]] = [
    {
        "key": "bbb",
        "name": "Better Business Bureau (BBB)",
        "category": "consumer mediation / business reputation",
        "recommended_channel": "web_form",
        "email": "",
        "web_url": "https://www.bbb.org/file-a-complaint",
        "notes": "Usually use BBB web complaint form. Do not email unless you have a verified BBB mailbox for the specific region.",
    },
    {
        "key": "state_ag",
        "name": "State Attorney General - Consumer Protection Division",
        "category": "state consumer protection / unfair or deceptive practice",
        "recommended_channel": "web_form_or_email_if_verified",
        "email": "",
        "web_url": "",
        "notes": "Use the consumer-protection complaint portal for the state where the transaction occurred. Add email manually only after verification.",
    },
    {
        "key": "state_attorney",
        "name": "Local State Attorney / District Attorney Consumer Protection Unit",
        "category": "local consumer fraud / criminal-pattern referral",
        "recommended_channel": "email_if_verified",
        "email": "",
        "web_url": "",
        "notes": "For suspected fraud patterns. Add the local official email manually after verification.",
    },
    {
        "key": "fdacs",
        "name": "Florida Department of Agriculture and Consumer Services (FDACS)",
        "category": "Florida consumer services",
        "recommended_channel": "web_form",
        "email": "",
        "web_url": "https://www.fdacs.gov/Contact-Us/File-a-Complaint",
        "notes": "For Florida consumer-service complaints. Usually a web form.",
    },
    {
        "key": "ftc",
        "name": "Federal Trade Commission (FTC) ReportFraud",
        "category": "federal deceptive-practice reporting",
        "recommended_channel": "web_form",
        "email": "",
        "web_url": "https://reportfraud.ftc.gov/",
        "notes": "Useful for national-pattern reporting. Usually a web form, not email.",
    },
    {
        "key": "ic3",
        "name": "FBI Internet Crime Complaint Center (IC3)",
        "category": "internet-enabled fraud reporting",
        "recommended_channel": "web_form",
        "email": "",
        "web_url": "https://www.ic3.gov/",
        "notes": "Use when online booking/payment/aggregator conduct is part of the alleged fraud.",
    },
    {
        "key": "credit_card",
        "name": "Credit Card Issuer - Billing Dispute / Chargeback Department",
        "category": "payment dispute / chargeback",
        "recommended_channel": "secure_message_or_mail",
        "email": "",
        "web_url": "",
        "notes": "Usually use bank portal, secure message, phone, or written FCBA notice. Add email only if verified by issuer.",
    },
    {
        "key": "company_exec",
        "name": "Company Executive / Legal / Customer Relations Escalation",
        "category": "direct merchant escalation",
        "recommended_channel": "email_if_verified",
        "email": "",
        "web_url": "",
        "notes": "Add verified company escalation email manually.",
    },
]


# -----------------------------------------------------------------------------
# Data models
# -----------------------------------------------------------------------------
@dataclass
class ComplaintRecord:
    complaint_id: str
    subject: str
    complaint_text: str
    professional_text: str = ""
    company_name: str = ""
    user_name: str = ""
    user_email: str = ""
    created_at: str = ""
    docs: List[str] | None = None
    source_table: str = ""
    raw_json: Dict[str, Any] | None = None

    def display_text(self) -> str:
        return self.professional_text or self.complaint_text


@dataclass
class OutreachDraft:
    include: bool
    org_key: str
    org_name: str
    category: str
    recommended_channel: str
    email: str
    web_url: str
    why_this_org: str
    subject: str
    body: str
    caution: str = ""


# -----------------------------------------------------------------------------
# SQLite helpers
# -----------------------------------------------------------------------------
def open_db(db_path: str) -> sqlite3.Connection:
    if not db_path:
        raise ValueError("Database path is required.")
    if not os.path.exists(db_path):
        raise FileNotFoundError(f"Database not found: {db_path}")
    con = sqlite3.connect(db_path, check_same_thread=False)
    con.row_factory = sqlite3.Row
    return con


def table_columns(con: sqlite3.Connection, table: str) -> List[str]:
    return [r[1] for r in con.execute(f"PRAGMA table_info('{table}')").fetchall()]


def list_tables(con: sqlite3.Connection) -> List[str]:
    rows = con.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return [r[0] for r in rows]


def json_loads_safe(s: Any) -> Dict[str, Any]:
    if isinstance(s, dict):
        return s
    if not s:
        return {}
    try:
        x = json.loads(s)
        return x if isinstance(x, dict) else {}
    except Exception:
        return {}


def clean_text(x: Any) -> str:
    if x is None:
        return ""
    text = str(x).replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def first_existing_key(d: Dict[str, Any], keys: List[str]) -> str:
    for k in keys:
        v = clean_text(d.get(k))
        if v:
            return v
    return ""


def infer_company_name(text: str, subject: str = "") -> str:
    # Lightweight inference only. The user can always override.
    combined = f"{subject}\n{text}"
    patterns = [
        r"(?:against|from|with|by)\s+([A-Z][A-Za-z0-9&.'\- ]{2,80})(?:\s+for|\s+because|\s+regarding|[,.;\n]|$)",
        r"company\s+(?:called|named)\s+([A-Z][A-Za-z0-9&.'\- ]{2,80})(?:[,.;\n]|$)",
        r"merchant\s+(?:called|named)\s+([A-Z][A-Za-z0-9&.'\- ]{2,80})(?:[,.;\n]|$)",
    ]
    for pat in patterns:
        m = re.search(pat, combined, flags=re.IGNORECASE)
        if m:
            candidate = re.sub(r"\s+", " ", m.group(1)).strip(" .,-")
            if 2 <= len(candidate) <= 80:
                return candidate
    return ""


def load_complaint_warrior_native(con: sqlite3.Connection) -> List[ComplaintRecord]:
    """Load the native Complaint Warrior table: complaints(user_email, complaint_id, complaint_json, updated_at)."""
    rows = con.execute(
        "SELECT user_email, complaint_id, complaint_json, updated_at FROM complaints ORDER BY updated_at DESC"
    ).fetchall()
    out: List[ComplaintRecord] = []
    for row in rows:
        obj = json_loads_safe(row["complaint_json"])
        raw = clean_text(obj.get("complaint_raw"))
        prof = clean_text(obj.get("complaint_professional"))
        subject = clean_text(obj.get("subject")) or "Consumer complaint"
        company = first_existing_key(obj, ["company_name", "merchant_name", "business_name"])
        if not company:
            company = infer_company_name(raw or prof, subject)
        out.append(
            ComplaintRecord(
                complaint_id=clean_text(row["complaint_id"]) or clean_text(obj.get("complaint_id")),
                subject=subject,
                complaint_text=raw or prof,
                professional_text=prof,
                company_name=company,
                user_name=clean_text(obj.get("user_name")),
                user_email=clean_text(obj.get("user_email")) or clean_text(row["user_email"]),
                created_at=clean_text(obj.get("created_at")),
                docs=obj.get("docs") or [],
                source_table="complaints",
                raw_json=obj,
            )
        )
    return out


def pick_generic_columns(columns: List[str]) -> Dict[str, Optional[str]]:
    norm = {re.sub(r"[^a-z0-9]", "", c.lower()): c for c in columns}

    def find(names: List[str]) -> Optional[str]:
        for n in names:
            hit = norm.get(re.sub(r"[^a-z0-9]", "", n.lower()))
            if hit:
                return hit
        # fallback substring
        for k, original in norm.items():
            if any(re.sub(r"[^a-z0-9]", "", n.lower()) in k for n in names):
                return original
        return None

    return {
        "id": find(["complaint_id", "case_id", "id", "claim_id"]),
        "subject": find(["subject", "title", "issue", "case_title"]),
        "text": find(["complaint", "complaint_text", "complaint_raw", "description", "issue_summary", "claim_summary"]),
        "professional": find(["complaint_professional", "professional_text", "final_text"]),
        "company": find(["company_name", "merchant", "merchant_name", "business_name", "defendant"]),
        "user_name": find(["user_name", "consumer_name", "customer_name", "plaintiff_name"]),
        "user_email": find(["user_email", "consumer_email", "customer_email", "email"]),
        "created_at": find(["created_at", "created", "date", "updated_at"]),
    }


def load_generic_complaints(con: sqlite3.Connection) -> Tuple[List[ComplaintRecord], str, Dict[str, Optional[str]]]:
    tables = list_tables(con)
    best = None
    best_score = -1
    for t in tables:
        cols = table_columns(con, t)
        mapping = pick_generic_columns(cols)
        score = sum(1 for v in mapping.values() if v)
        if score > best_score and mapping.get("text"):
            best = t
            best_score = score
    if not best:
        return [], "", {}

    mapping = pick_generic_columns(table_columns(con, best))
    rows = con.execute(f"SELECT * FROM '{best}' ORDER BY rowid DESC LIMIT 250").fetchall()
    records: List[ComplaintRecord] = []
    for i, row in enumerate(rows):
        d = dict(row)
        subject = clean_text(d.get(mapping.get("subject") or "")) or "Consumer complaint"
        text = clean_text(d.get(mapping.get("text") or ""))
        prof = clean_text(d.get(mapping.get("professional") or ""))
        company = clean_text(d.get(mapping.get("company") or "")) or infer_company_name(text or prof, subject)
        cid = clean_text(d.get(mapping.get("id") or "")) or f"ROW-{i+1}"
        records.append(
            ComplaintRecord(
                complaint_id=cid,
                subject=subject,
                complaint_text=text or prof,
                professional_text=prof,
                company_name=company,
                user_name=clean_text(d.get(mapping.get("user_name") or "")),
                user_email=clean_text(d.get(mapping.get("user_email") or "")),
                created_at=clean_text(d.get(mapping.get("created_at") or "")),
                docs=[],
                source_table=best,
                raw_json=d,
            )
        )
    return records, best, mapping


def load_complaints(db_path: str) -> Tuple[List[ComplaintRecord], str, Dict[str, Any]]:
    con = open_db(db_path)
    try:
        tables = list_tables(con)
        if "complaints" in tables:
            cols = set(table_columns(con, "complaints"))
            if {"complaint_id", "complaint_json"}.issubset(cols):
                return load_complaint_warrior_native(con), "Complaint Warrior native complaints table", {}
        records, table, mapping = load_generic_complaints(con)
        return records, f"Generic table: {table}" if table else "No complaint table detected", mapping
    finally:
        con.close()


def ensure_outreach_table(con: sqlite3.Connection) -> None:
    con.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {OUTREACH_TABLE} (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            complaint_id TEXT NOT NULL,
            org_key TEXT,
            org_name TEXT NOT NULL,
            recipient_email TEXT,
            channel TEXT NOT NULL,
            subject TEXT,
            body TEXT,
            gmail_message_id TEXT,
            status TEXT NOT NULL,
            error TEXT,
            sent_at REAL NOT NULL,
            created_at_iso TEXT NOT NULL
        )
        """
    )
    con.commit()


def log_outreach(
    db_path: str,
    complaint_id: str,
    draft: OutreachDraft,
    status: str,
    gmail_message_id: str = "",
    error: str = "",
) -> None:
    con = open_db(db_path)
    try:
        ensure_outreach_table(con)
        now = time.time()
        con.execute(
            f"""
            INSERT INTO {OUTREACH_TABLE} (
                complaint_id, org_key, org_name, recipient_email, channel, subject, body,
                gmail_message_id, status, error, sent_at, created_at_iso
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                complaint_id,
                draft.org_key,
                draft.org_name,
                draft.email,
                draft.recommended_channel,
                draft.subject,
                draft.body,
                gmail_message_id,
                status,
                error,
                now,
                datetime.fromtimestamp(now).isoformat(timespec="seconds"),
            ),
        )
        con.commit()
    finally:
        con.close()



# -----------------------------------------------------------------------------
# Complaint Warrior native status update helper
# -----------------------------------------------------------------------------
MODULE_STATUS_LABELS = {
    "resolved": "Resolved",
    "social_network_shared": "Social network shared",
    "charge_back_initiated": "Charge-back initiated",
    "submitted_to_small_claim_court": "Submitted to small claim court",
    "escalated_to_authorities": "Escalated to authorities",
}

def update_native_complaint_module_status(
    db_path: str,
    complaint_id: str,
    status_key: str,
    note: str = "",
    meta: Optional[Dict[str, Any]] = None,
) -> bool:
    """Update Complaint Warrior native complaints.complaint_json.

    This lets external modules update cw_store.sqlite without importing the
    main Streamlit manager or requiring an active Streamlit session from
    cw_app_phone.py.
    """
    if status_key not in MODULE_STATUS_LABELS or not db_path or not complaint_id:
        return False
    if not os.path.exists(db_path):
        return False

    label = MODULE_STATUS_LABELS[status_key]
    now_iso = datetime.now().isoformat(timespec="seconds")
    con = sqlite3.connect(db_path)
    try:
        cols = [r[1] for r in con.execute("PRAGMA table_info('complaints')").fetchall()]
        if "complaint_id" not in cols or "complaint_json" not in cols:
            return False
        row = con.execute(
            "SELECT complaint_json FROM complaints WHERE complaint_id=? LIMIT 1",
            (complaint_id,),
        ).fetchone()
        if not row:
            return False
        obj = json_loads_safe(row[0])
        statuses = obj.get("module_statuses")
        if not isinstance(statuses, dict):
            statuses = {}
        for key, key_label in MODULE_STATUS_LABELS.items():
            statuses.setdefault(key, {"done": False, "label": key_label, "updated_at": None, "note": ""})
            if isinstance(statuses[key], dict):
                statuses[key]["label"] = key_label
            else:
                statuses[key] = {"done": bool(statuses[key]), "label": key_label, "updated_at": None, "note": ""}
        statuses[status_key].update({
            "done": True,
            "label": label,
            "updated_at": now_iso,
            "note": note or "",
        })
        obj["module_statuses"] = statuses
        resolved_done = bool((statuses.get("resolved") or {}).get("done"))
        already_resolved = resolved_done or "resolved" in str(obj.get("final_conclusion", "")).lower()
        if not already_resolved:
            obj["current_status_summary"] = label
            if status_key == "escalated_to_authorities":
                obj["final_conclusion"] = "Escalated to authorities; awaiting agency response."
                for thread in (obj.get("threads") or {}).values():
                    if isinstance(thread, dict):
                        thread["status"] = "waiting_external_reply"
                        thread["stage"] = "escalated_to_authorities"
                        thread["drafts"] = []
                        thread["last_decision"] = None
        activities = obj.get("activities")
        if not isinstance(activities, list):
            activities = []
        activities.append({
            "ts": now_iso,
            "channel": "regulatory",
            "kind": "status",
            "title": label,
            "detail": note or "Regulatory escalation submitted or recorded.",
            "meta": {"status_key": status_key, **(meta or {})},
        })
        obj["activities"] = activities
        con.execute(
            "UPDATE complaints SET complaint_json=?, updated_at=? WHERE complaint_id=?",
            (json.dumps(obj, ensure_ascii=False), time.time(), complaint_id),
        )
        con.commit()
        return True
    finally:
        con.close()

# -----------------------------------------------------------------------------
# OpenAI routing and drafting
# -----------------------------------------------------------------------------
def fallback_rule_based_drafts(record: ComplaintRecord, registry: List[Dict[str, str]]) -> List[OutreachDraft]:
    """Works without OpenAI. Uses registry and a standard complaint letter."""
    company = record.company_name or "the company"
    selected_keys = ["bbb", "state_ag", "ftc", "credit_card", "company_exec"]
    text = record.display_text()
    drafts: List[OutreachDraft] = []
    for org in registry:
        if org["key"] not in selected_keys:
            continue
        org_name = org["name"]
        subject = f"Consumer complaint regarding {company}"
        body = f"""Dear {org_name},

I am submitting this consumer complaint regarding {company}.

Summary of complaint:
{text}

Requested resolution:
I request investigation, mediation, or appropriate referral, and I request that {company} refund any undisclosed or improperly imposed charges and provide a written explanation of the transaction.

Basis for complaint:
The issue involves an alleged undisclosed mandatory charge, refusal to honor prepaid or represented terms, and possible unfair or deceptive business practice. I am preserving receipts, reservation confirmations, screenshots, and related correspondence as supporting evidence.

Please confirm receipt of this complaint and advise if additional documentation is required.

Sincerely,
{record.user_name or '[Your name]'}
{record.user_email or ''}
""".strip()
        drafts.append(
            OutreachDraft(
                include=True,
                org_key=org["key"],
                org_name=org_name,
                category=org.get("category", ""),
                recommended_channel=org.get("recommended_channel", ""),
                email=org.get("email", ""),
                web_url=org.get("web_url", ""),
                why_this_org=org.get("notes", ""),
                subject=subject,
                body=body,
                caution="Email is empty unless verified. Use web form/copy-paste where applicable.",
            )
        )
    return drafts


def extract_json_object(text: str) -> Dict[str, Any]:
    text = text.strip()
    try:
        return json.loads(text)
    except Exception:
        pass
    m = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not m:
        raise ValueError("Model did not return JSON.")
    return json.loads(m.group(0))


def generate_outreach_drafts_with_openai(
    record: ComplaintRecord,
    registry: List[Dict[str, str]],
    jurisdiction_hint: str,
    extra_instruction: str,
) -> List[OutreachDraft]:
    if OpenAI is None:
        raise RuntimeError("OpenAI package is not installed. Run: pip install openai")
    api_key = get_openai_api_key()
    if not api_key:
        raise RuntimeError("OpenAI API key not found. Put it in ./config.ini as [OpenAI] api_key = ...")

    client = OpenAI(api_key=api_key)
    complaint_payload = {
        "complaint_id": record.complaint_id,
        "subject": record.subject,
        "company_name": record.company_name,
        "user_name": record.user_name,
        "user_email": record.user_email,
        "complaint_text": record.display_text(),
        "jurisdiction_hint": jurisdiction_hint,
    }
    system = """You are a careful U.S. consumer-complaint routing and drafting assistant.
Return STRICT JSON only.
Your task: recommend organizations to contact and draft individualized complaint letters.
Rules:
- Do not provide legal advice as an attorney.
- Do not invent recipient email addresses.
- If an organization normally uses a web form, set email to empty and recommended_channel to web_form.
- Only use emails already present in the provided organization registry or explicitly present in the complaint/user instruction.
- Use cautious language: suspected, alleged, appears, I believe. Do not conclusively accuse anyone of a crime.
- Avoid defamation and exaggeration. Keep facts specific and verifiable.
- Each letter should request a concrete remedy, confirmation of receipt, and instructions for evidence submission.
- For BBB, FTC, state AG, FDACS, IC3, etc., drafts may be used as web-form text.
JSON shape:
{
  "drafts": [
    {
      "include": true,
      "org_key": "registry key or extra_org",
      "org_name": "name",
      "category": "category",
      "recommended_channel": "email_if_verified|web_form|secure_message_or_mail|manual",
      "email": "verified email or empty string",
      "web_url": "url or empty string",
      "why_this_org": "1-2 sentence reason",
      "subject": "email/form subject",
      "body": "full complaint letter",
      "caution": "any review warning"
    }
  ]
}
"""
    user = {
        "complaint": complaint_payload,
        "organization_registry": registry,
        "extra_instruction": extra_instruction,
    }
    resp = client.chat.completions.create(
        model=OPENAI_MODEL,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": json.dumps(user, ensure_ascii=False, indent=2)},
        ],
        temperature=0.2,
        response_format={"type": "json_object"},
    )
    raw = resp.choices[0].message.content or "{}"
    parsed = extract_json_object(raw)
    drafts: List[OutreachDraft] = []

    # Preserve known email/web metadata from registry. GPT can explain and draft, but
    # verified recipient data should come from registry/user review.
    by_key = {o["key"]: o for o in registry}
    for item in parsed.get("drafts", []):
        if not isinstance(item, dict):
            continue
        key = clean_text(item.get("org_key"))
        reg = by_key.get(key, {})
        email = clean_text(reg.get("email")) or clean_text(item.get("email"))
        # If GPT supplied an email that was not in registry, keep it but force review.
        caution = clean_text(item.get("caution"))
        if email and not clean_text(reg.get("email")):
            caution = (caution + "\n" if caution else "") + "GPT/user-supplied email: verify before sending."
        drafts.append(
            OutreachDraft(
                include=bool(item.get("include", True)),
                org_key=key or "extra_org",
                org_name=clean_text(item.get("org_name")) or clean_text(reg.get("name")) or "Organization",
                category=clean_text(item.get("category")) or clean_text(reg.get("category")),
                recommended_channel=clean_text(item.get("recommended_channel")) or clean_text(reg.get("recommended_channel")),
                email=email,
                web_url=clean_text(reg.get("web_url")) or clean_text(item.get("web_url")),
                why_this_org=clean_text(item.get("why_this_org")) or clean_text(reg.get("notes")),
                subject=clean_text(item.get("subject")) or f"Consumer complaint regarding {record.company_name or 'merchant'}",
                body=clean_text(item.get("body")),
                caution=caution,
            )
        )
    if not drafts:
        raise ValueError("OpenAI returned no drafts.")
    return drafts


# -----------------------------------------------------------------------------
# Gmail helpers
# -----------------------------------------------------------------------------
def is_invalid_grant_error(exc: BaseException) -> bool:
    """True when Google rejected the refresh token and re-auth is required."""
    text = f"{type(exc).__name__}: {exc}".lower()
    return "invalid_grant" in text or "token has been expired or revoked" in text


def _safe_unlink(path: str) -> None:
    if path:
        try:
            Path(path).unlink(missing_ok=True)
        except Exception:
            pass


def _load_token_from_sqlite(token_db_path: str, token_key: str) -> Tuple[Optional[str], Optional[Dict[str, Any]]]:
    """Read a Gmail OAuth token stored by gmail_oauth_server.py / GmailTokenStore."""
    if not token_db_path or not os.path.exists(token_db_path):
        return None, None
    con = sqlite3.connect(token_db_path)
    try:
        rows = con.execute("SELECT key, token_json FROM gmail_tokens ORDER BY updated_at DESC").fetchall()
    except Exception:
        return None, None
    finally:
        con.close()
    if not rows:
        return None, None

    # Prefer configured key. If it does not exist and there is only one account, use that account.
    for key, token_json in rows:
        if key == token_key:
            return key, json_loads_safe(token_json)
    if len(rows) == 1:
        return rows[0][0], json_loads_safe(rows[0][1])
    return None, None


def _delete_sqlite_token(token_db_path: str, token_key: str) -> None:
    if not token_db_path or not os.path.exists(token_db_path) or not token_key:
        return
    try:
        con = sqlite3.connect(token_db_path)
        con.execute("DELETE FROM gmail_tokens WHERE key=?", (token_key,))
        con.commit()
        con.close()
    except Exception:
        pass


def _save_token_to_sqlite(token_db_path: str, token_key: str, token_json: Dict[str, Any]) -> None:
    con = sqlite3.connect(token_db_path)
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS gmail_tokens(
          key TEXT PRIMARY KEY,
          token_json TEXT NOT NULL,
          updated_at REAL NOT NULL
        )
        """
    )
    con.execute(
        "INSERT OR REPLACE INTO gmail_tokens(key, token_json, updated_at) VALUES(?,?,?)",
        (token_key, json.dumps(token_json), time.time()),
    )
    con.commit()
    con.close()


def list_gmail_token_keys(token_db_path: str = GMAIL_TOKEN_DB) -> List[str]:
    if not token_db_path or not os.path.exists(token_db_path):
        return []
    con = sqlite3.connect(token_db_path)
    try:
        rows = con.execute("SELECT key FROM gmail_tokens ORDER BY updated_at DESC").fetchall()
        return [r[0] for r in rows]
    except Exception:
        return []
    finally:
        con.close()


def _credentials_to_token_json(creds: Any) -> Dict[str, Any]:
    return {
        "token": getattr(creds, "token", None),
        "refresh_token": getattr(creds, "refresh_token", None),
        "token_uri": getattr(creds, "token_uri", None),
        "client_id": getattr(creds, "client_id", None),
        "client_secret": getattr(creds, "client_secret", None),
        "scopes": list(getattr(creds, "scopes", None) or SCOPES),
    }


def _creds_from_token_json(token_json: Dict[str, Any]) -> Any:
    return Credentials(
        token=token_json.get("token"),
        refresh_token=token_json.get("refresh_token"),
        token_uri=token_json.get("token_uri"),
        client_id=token_json.get("client_id"),
        client_secret=token_json.get("client_secret"),
        scopes=token_json.get("scopes") or SCOPES,
    )


def _refresh_or_raise_invalid_grant(creds: Any) -> Any:
    """Refresh proactively so invalid_grant is detected before the first send."""
    if not creds:
        return creds
    if getattr(creds, "refresh_token", None):
        creds.refresh(Request())
    return creds


def _run_local_oauth(client_secrets_path: str, token_path: str, token_db_path: str, token_key: str, token_pickle_path: str) -> Any:
    """Start local browser OAuth and save the fresh token to json, sqlite, and pickle fallbacks."""
    if not os.path.exists(client_secrets_path):
        raise FileNotFoundError(
            f"Gmail OAuth credentials not found: {client_secrets_path}. Put credentials.json in the app directory."
        )
    flow = InstalledAppFlow.from_client_secrets_file(client_secrets_path, SCOPES)
    creds = flow.run_local_server(port=0)

    # Save modern JSON token.
    if token_path:
        Path(token_path).write_text(creds.to_json(), encoding="utf-8")

    # Save SQLite token compatible with your gmail_oauth_server.py / GmailTokenStore pattern.
    token_json = _credentials_to_token_json(creds)
    if token_db_path and token_key:
        _save_token_to_sqlite(token_db_path, token_key, token_json)

    # Save legacy pickle compatible with auth_gmail.py.
    if token_pickle_path:
        with open(token_pickle_path, "wb") as f:
            pickle.dump(creds, f)

    return creds


def build_gmail_service(
    client_secrets_path: str = GMAIL_CLIENT_SECRETS,
    token_path: str = GMAIL_TOKEN_FILE,
    token_db_path: str = GMAIL_TOKEN_DB,
    token_key: str = GMAIL_TOKEN_KEY,
    token_pickle_path: str = GMAIL_TOKEN_PICKLE,
    force_reauth: bool = False,
):
    """Build Gmail API service using local files in the app directory.

    This version handles invalid_grant by deleting the bad saved token and starting OAuth again.

    Preferred order:
      1. cw_gmail_tokens.sqlite created by gmail_oauth_server.py / GmailTokenStore.
      2. gmail_token.json created by this app.
      3. token.pickle created by the simple auth_gmail.py helper.
      4. Fresh local OAuth through credentials.json.
    """
    if Credentials is None or build is None or InstalledAppFlow is None:
        raise RuntimeError(
            "Google API packages are not installed. Run: pip install google-api-python-client google-auth-oauthlib google-auth-httplib2"
        )

    if force_reauth:
        _delete_sqlite_token(token_db_path, token_key)
        _delete_sqlite_token(token_db_path, "default")
        _safe_unlink(token_path)
        _safe_unlink(token_pickle_path)

    # 1) SQLite token from gmail_oauth_server.py.
    selected_key, token_json = _load_token_from_sqlite(token_db_path, token_key)
    if token_json:
        try:
            creds = _creds_from_token_json(token_json)
            # Proactively refresh to catch invalid_grant now, not during send().
            creds = _refresh_or_raise_invalid_grant(creds)
            refreshed = _credentials_to_token_json(creds)
            _save_token_to_sqlite(token_db_path, selected_key or token_key, refreshed)
            if creds and creds.valid:
                return build("gmail", "v1", credentials=creds, cache_discovery=False)
        except Exception as e:
            if is_invalid_grant_error(e):
                _delete_sqlite_token(token_db_path, selected_key or token_key)
            else:
                raise

    # 2) JSON token fallback.
    token_file = Path(token_path)
    if token_file.exists():
        try:
            creds = Credentials.from_authorized_user_file(str(token_file), SCOPES)
            if getattr(creds, "refresh_token", None):
                creds = _refresh_or_raise_invalid_grant(creds)
                token_file.write_text(creds.to_json(), encoding="utf-8")
            if creds and creds.valid:
                return build("gmail", "v1", credentials=creds, cache_discovery=False)
        except Exception as e:
            if is_invalid_grant_error(e):
                _safe_unlink(token_path)
            else:
                raise

    # 3) token.pickle fallback from auth_gmail.py.
    pickle_file = Path(token_pickle_path)
    if pickle_file.exists():
        try:
            with open(pickle_file, "rb") as f:
                creds = pickle.load(f)
            if getattr(creds, "refresh_token", None):
                creds = _refresh_or_raise_invalid_grant(creds)
                with open(pickle_file, "wb") as f:
                    pickle.dump(creds, f)
            if creds and creds.valid:
                return build("gmail", "v1", credentials=creds, cache_discovery=False)
        except Exception as e:
            if is_invalid_grant_error(e):
                _safe_unlink(token_pickle_path)
            else:
                raise

    # 4) Fresh OAuth when all saved tokens are missing/revoked/expired.
    creds = _run_local_oauth(client_secrets_path, token_path, token_db_path, token_key, token_pickle_path)
    return build("gmail", "v1", credentials=creds, cache_discovery=False)


def make_gmail_message(
    to_email: str,
    subject: str,
    body_text: str,
    attachments: Optional[List[Tuple[str, bytes]]] = None,
) -> Dict[str, str]:
    attachments = attachments or []
    msg = MIMEMultipart()
    msg["To"] = to_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body_text, "plain", "utf-8"))

    for filename, data in attachments:
        ctype, encoding = mimetypes.guess_type(filename)
        if ctype is None or encoding is not None:
            ctype = "application/octet-stream"
        maintype, subtype = ctype.split("/", 1)
        part = MIMEBase(maintype, subtype)
        part.set_payload(data)
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", "attachment", filename=os.path.basename(filename))
        msg.attach(part)

    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode("utf-8")
    return {"raw": raw}


def gmail_send(
    service: Any,
    to_email: str,
    subject: str,
    body_text: str,
    attachments: Optional[List[Tuple[str, bytes]]] = None,
) -> Dict[str, Any]:
    body = make_gmail_message(to_email, subject, body_text, attachments)
    return service.users().messages().send(userId="me", body=body).execute()


def gmail_send_with_reauth(
    to_email: str,
    subject: str,
    body_text: str,
    attachments: Optional[List[Tuple[str, bytes]]] = None,
) -> Dict[str, Any]:
    """Send once, and if invalid_grant occurs, force OAuth re-connect and retry once."""
    service = build_gmail_service(
        GMAIL_CLIENT_SECRETS,
        GMAIL_TOKEN_FILE,
        GMAIL_TOKEN_DB,
        GMAIL_TOKEN_KEY,
        GMAIL_TOKEN_PICKLE,
        force_reauth=False,
    )
    try:
        return gmail_send(service, to_email, subject, body_text, attachments=attachments)
    except Exception as e:
        if not is_invalid_grant_error(e):
            raise
        # Saved token was revoked/expired. Delete bad tokens, re-authenticate, retry exactly once.
        service = build_gmail_service(
            GMAIL_CLIENT_SECRETS,
            GMAIL_TOKEN_FILE,
            GMAIL_TOKEN_DB,
            GMAIL_TOKEN_KEY,
            GMAIL_TOKEN_PICKLE,
            force_reauth=True,
        )
        return gmail_send(service, to_email, subject, body_text, attachments=attachments)


# -----------------------------------------------------------------------------
# Streamlit state helpers
# -----------------------------------------------------------------------------
def init_state() -> None:
    st.session_state.setdefault("all_records", [])
    st.session_state.setdefault("records", [])
    st.session_state.setdefault("selected_user_email", "")
    st.session_state.setdefault("selected_complaint_id", "")
    st.session_state.setdefault("drafts", [])
    st.session_state.setdefault("registry", DEFAULT_ORG_REGISTRY.copy())
    st.session_state.setdefault("loaded_db_path", "")
    st.session_state.setdefault("db_source", "")
    st.session_state.setdefault("generic_mapping", {})


def complaint_option_label(record: ComplaintRecord) -> str:
    title = clean_text(record.subject) or clean_text(record.company_name) or "Untitled complaint"
    if len(title) > 90:
        title = title[:87].rstrip() + "..."
    return f"{record.complaint_id} — {title}"


def records_to_df(records: List[ComplaintRecord]) -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "select": "",
                "complaint_id": r.complaint_id,
                "title": r.subject,
                "company_name": r.company_name,
                "user_email": r.user_email,
                "created_at": r.created_at,
                "preview": (r.display_text() or "")[:160],
                "source_table": r.source_table,
            }
            for r in records
        ]
    )

def get_selected_record() -> Optional[ComplaintRecord]:
    cid = st.session_state.get("selected_complaint_id")
    for r in st.session_state.get("records", []):
        if r.complaint_id == cid:
            return r
    return None


def upload_attachments_to_memory(uploaded_files) -> List[Tuple[str, bytes]]:
    out: List[Tuple[str, bytes]] = []
    for f in uploaded_files or []:
        out.append((f.name, f.getvalue()))
    return out


def parse_registry_csv(uploaded) -> Optional[List[Dict[str, str]]]:
    if not uploaded:
        return None
    df = pd.read_csv(uploaded).fillna("")
    required = {"key", "name"}
    if not required.issubset(set(df.columns)):
        raise ValueError("Registry CSV must contain at least columns: key,name")
    rows = []
    for _, row in df.iterrows():
        d = {k: clean_text(row.get(k, "")) for k in df.columns}
        for k in ["category", "recommended_channel", "email", "web_url", "notes"]:
            d.setdefault(k, "")
        rows.append(d)
    return rows


def load_registry_from_config() -> List[Dict[str, str]]:
    """Load an optional organization registry from config.ini.

    Supported:
      [Registry]
      path = organizations.csv

    CSV columns: key,name,category,recommended_channel,email,web_url,notes
    JSON format: a list of objects with the same keys.

    If no file is configured or the file is missing, the built-in registry is used.
    """
    registry_path = local_path(cfg_get("Registry", "path", ""))
    if not registry_path:
        return DEFAULT_ORG_REGISTRY.copy()

    p = Path(registry_path)
    if not p.exists():
        st.warning(f"Registry file configured but not found: {registry_path}. Using default registry.")
        return DEFAULT_ORG_REGISTRY.copy()

    try:
        if p.suffix.lower() == ".json":
            data = json.loads(p.read_text(encoding="utf-8"))
            if not isinstance(data, list):
                raise ValueError("Registry JSON must be a list of objects.")
            rows = []
            for item in data:
                if not isinstance(item, dict):
                    continue
                d = {str(k): clean_text(v) for k, v in item.items()}
                if not d.get("key") or not d.get("name"):
                    continue
                for k in ["category", "recommended_channel", "email", "web_url", "notes"]:
                    d.setdefault(k, "")
                rows.append(d)
            return rows or DEFAULT_ORG_REGISTRY.copy()

        df = pd.read_csv(p).fillna("")
        required = {"key", "name"}
        if not required.issubset(set(df.columns)):
            raise ValueError("Registry CSV must contain at least columns: key,name")
        rows = []
        for _, row in df.iterrows():
            d = {k: clean_text(row.get(k, "")) for k in df.columns}
            for k in ["category", "recommended_channel", "email", "web_url", "notes"]:
                d.setdefault(k, "")
            rows.append(d)
        return rows or DEFAULT_ORG_REGISTRY.copy()
    except Exception as e:
        st.warning(f"Could not load organization registry from {registry_path}: {e}. Using default registry.")
        return DEFAULT_ORG_REGISTRY.copy()


def parse_config_paths(value: str) -> List[str]:
    """Parse comma/newline/semicolon-separated paths from config.ini."""
    value = clean_text(value)
    if not value:
        return []
    parts = re.split(r"[\n;,]+", value)
    return [local_path(x.strip()) for x in parts if x.strip()]


def load_attachment_files_for_record(record: ComplaintRecord) -> List[Tuple[str, bytes]]:
    """Load evidence attachments automatically from the complaint JSON and config.ini.

    Sources:
      - record.docs from Complaint Warrior complaint_json
      - [Attachments] paths = file1.pdf, file2.png
      - [Attachments] directory = cw_uploads

    Missing files are skipped with a visible warning.
    """
    candidates: List[str] = []

    for p in record.docs or []:
        if p:
            candidates.append(local_path(str(p)))

    candidates.extend(parse_config_paths(cfg_get("Attachments", "paths", "")))

    directory = local_path(cfg_get("Attachments", "directory", ""))
    if directory and Path(directory).exists():
        for child in sorted(Path(directory).iterdir()):
            if child.is_file():
                candidates.append(str(child))

    seen = set()
    attachments: List[Tuple[str, bytes]] = []
    missing: List[str] = []
    for item in candidates:
        if not item:
            continue
        p = Path(item)
        key = str(p.resolve()) if p.exists() else str(p)
        if key in seen:
            continue
        seen.add(key)
        if not p.exists() or not p.is_file():
            missing.append(str(p))
            continue
        try:
            attachments.append((p.name, p.read_bytes()))
        except Exception as e:
            st.warning(f"Could not read attachment {p}: {e}")

    if missing:
        with st.expander("Some configured evidence files were not found", expanded=False):
            for m in missing:
                st.write(m)

    return attachments


def auto_load_complaints_once() -> None:
    """Load all complaints from config/database path.

    IMPORTANT: this function does not expose all complaints in the UI. It loads
    them into memory only so the user can explicitly choose a user/email filter
    before any complaint grid is displayed.
    """
    db_path = DEFAULT_DB_PATH
    already_loaded = bool(st.session_state.get("all_records")) and st.session_state.get("loaded_db_path") == db_path
    attempted = st.session_state.get("auto_load_attempted_for") == db_path
    if already_loaded or attempted:
        return

    st.session_state.auto_load_attempted_for = db_path
    try:
        records, source, mapping = load_complaints(db_path)
        st.session_state.all_records = records
        st.session_state.records = []
        st.session_state.loaded_db_path = db_path
        st.session_state.db_source = source
        st.session_state.generic_mapping = mapping
        st.session_state.registry = load_registry_from_config()
        st.session_state.drafts = []

    except Exception as e:
        st.session_state.auto_load_error = str(e)


def _available_user_emails(records: List[ComplaintRecord]) -> List[str]:
    return sorted({(r.user_email or "").strip().lower() for r in records if (r.user_email or "").strip()})


def _apply_selected_user_filter() -> None:
    selected = (st.session_state.get("selected_user_email") or "").strip().lower()
    all_records = st.session_state.get("all_records") or []
    if not selected:
        st.session_state.records = []
        st.session_state.selected_complaint_id = ""
        st.session_state.drafts = []
        return

    filtered = [r for r in all_records if (r.user_email or "").strip().lower() == selected]
    previous_cid = st.session_state.get("selected_complaint_id", "")
    st.session_state.records = filtered
    if previous_cid not in {r.complaint_id for r in filtered}:
        st.session_state.selected_complaint_id = filtered[0].complaint_id if filtered else ""
        st.session_state.drafts = []


# -----------------------------------------------------------------------------
# Main UI
# -----------------------------------------------------------------------------
def main() -> None:
    st.set_page_config(page_title=APP_TITLE, layout="centered", initial_sidebar_state="collapsed")
    init_state()

    # Hard-hide Streamlit sidebar/navigation shell. This app is fully config-driven.
    st.markdown(
        """
        <style>
        [data-testid="stSidebar"], [data-testid="stSidebarNav"], section[data-testid="stSidebar"] {
            display: none !important;
            width: 0 !important;
            min-width: 0 !important;
        }
        div[data-testid="collapsedControl"] {
            display: none !important;
        }
        .main .block-container {
            padding-left: 2rem;
            padding-right: 2rem;
            max-width: 1100px;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )

    auto_load_complaints_once()

    st.title(APP_TITLE)
    st.caption(
        "Configuration is loaded automatically from config.ini. The app reads cw_store.sqlite, generates organization outreach with ChatGPT, and sends selected verified emails through Gmail."
    )

    with st.expander("Loaded configuration", expanded=False):
        st.write(f"Config file: `{CONFIG_PATH}`")
        st.write(f"Database: `{DEFAULT_DB_PATH}`")
        st.write(f"OpenAI model: `{OPENAI_MODEL}`")
        st.write(f"Gmail credentials: `{GMAIL_CLIENT_SECRETS}`")
        st.write(f"Gmail token DB: `{GMAIL_TOKEN_DB}`")
        st.write(f"Gmail token key: `{GMAIL_TOKEN_KEY}`")
        st.write(f"Gmail token pickle fallback: `{GMAIL_TOKEN_PICKLE}`")
        registry_path = cfg_get("Registry", "path", "")
        if registry_path:
            st.write(f"Organization registry: `{local_path(registry_path)}`")
        attachments_dir = cfg_get("Attachments", "directory", "")
        attachments_paths = cfg_get("Attachments", "paths", "")
        if attachments_dir:
            st.write(f"Attachments directory: `{local_path(attachments_dir)}`")
        if attachments_paths:
            st.write("Configured attachment files are enabled.")

    if not get_openai_api_key():
        st.error("Missing OpenAI key. Add it to config.ini as: [OpenAI] api_key = ...")
        return

    if st.session_state.get("auto_load_error"):
        st.error(f"Could not load complaints automatically: {st.session_state.auto_load_error}")
        st.info("Check [Database] path in config.ini. Default expected file is cw_store.sqlite in the app directory.")
        with st.expander("Expected database formats"):
            st.markdown(
                """
                Supported formats:
                - Native Complaint Warrior: `complaints(user_email, complaint_id, complaint_json, updated_at)`.
                - Generic tables with columns like `complaint_id`, `subject`, `company_name`, `complaint_text`, `user_email`.
                """
            )
        return

    all_records = st.session_state.get("all_records") or []
    if not all_records:
        st.info("No complaints found in the configured database.")
        with st.expander("Expected database formats"):
            st.markdown(
                """
                Supported formats:
                - Native Complaint Warrior: `complaints(user_email, complaint_id, complaint_json, updated_at)`.
                - Generic tables with columns like `complaint_id`, `subject`, `company_name`, `complaint_text`, `user_email`.
                """
            )
        return

    st.success(f"Loaded complaint database from {st.session_state.db_source}.")
    if st.button("Refresh complaints from configured database"):
        st.session_state.all_records = []
        st.session_state.records = []
        st.session_state.selected_user_email = ""
        st.session_state.selected_complaint_id = ""
        st.session_state.drafts = []
        st.session_state.auto_load_error = ""
        st.session_state.auto_load_attempted_for = ""
        st.rerun()

    st.subheader("0) Enter Complaint Warrior user email")
    if not _available_user_emails(all_records):
        st.error("No user_email values were found in the complaints table. Refusing to show complaints without a user filter.")
        return

    current_selection = (st.session_state.get("selected_user_email") or "").strip().lower()
    selected_user = st.text_input(
        "Your Complaint Warrior email",
        value=current_selection,
        placeholder="you@example.com",
        help="Only complaints whose owner email exactly matches this value will be shown. Other users are never listed.",
    ).strip().lower()

    if selected_user != st.session_state.get("selected_user_email"):
        st.session_state.selected_user_email = selected_user
        _apply_selected_user_filter()
        st.rerun()

    st.session_state.selected_user_email = selected_user
    _apply_selected_user_filter()

    if not selected_user:
        st.warning("Enter your Complaint Warrior email. No complaints are shown until this field is filled.")
        return

    if not st.session_state.records:
        st.warning("No complaints found for this email. Nothing else is displayed.")
        return

    st.success(f"Showing {len(st.session_state.records)} complaint(s) for {selected_user}.")

    if st.session_state.generic_mapping:
        with st.expander("Detected generic database columns", expanded=False):
            st.json(st.session_state.generic_mapping)

    # 1) Select complaint
    st.subheader("1) Select complaint")
    df = records_to_df(st.session_state.records)

    st.caption(f"Showing only complaints for entered email: {st.session_state.selected_user_email}")

    grid_event = None
    try:
        grid_event = st.dataframe(
            df,
            use_container_width=True,
            hide_index=True,
            key="complaints_grid",
            on_select="rerun",
            selection_mode="single-row",
            column_config={
                "select": st.column_config.TextColumn("", width="small"),
                "complaint_id": st.column_config.TextColumn("Complaint ID", width="medium"),
                "title": st.column_config.TextColumn("Title", width="large"),
                "preview": st.column_config.TextColumn("Preview", width="large"),
            },
        )
    except TypeError:
        # Older Streamlit versions do not support row selection in st.dataframe.
        st.dataframe(df, use_container_width=True, hide_index=True)
        st.caption("Upgrade Streamlit to use row/cell click selection in the grid: pip install -U streamlit")

    if grid_event is not None:
        try:
            selected_rows = grid_event.selection.rows
            if selected_rows:
                selected_idx = int(selected_rows[0])
                if 0 <= selected_idx < len(st.session_state.records):
                    st.session_state.selected_complaint_id = st.session_state.records[selected_idx].complaint_id
        except Exception:
            pass

    option_by_label = {complaint_option_label(r): r.complaint_id for r in st.session_state.records}
    labels = list(option_by_label.keys())
    ids = list(option_by_label.values())
    if not st.session_state.selected_complaint_id and ids:
        st.session_state.selected_complaint_id = ids[0]

    current_label = next(
        (label for label, cid in option_by_label.items() if cid == st.session_state.selected_complaint_id),
        labels[0] if labels else "",
    )

    selected_label = st.selectbox(
        "Complaint",
        labels,
        index=labels.index(current_label) if current_label in labels else 0,
        help="The dropdown shows both the complaint ID and readable title. You can also select a row/cell in the grid above.",
    )
    st.session_state.selected_complaint_id = option_by_label.get(selected_label, st.session_state.selected_complaint_id)

    record = get_selected_record()
    if not record:
        st.error("No complaint selected.")
        return

    # Show complaint data as loaded. No path/config inputs are exposed.
    with st.expander("Complaint data loaded from database", expanded=True):
        st.write(f"Company / merchant: **{record.company_name or '[not detected]'}**")
        st.write(f"Consumer: **{record.user_name or '[not provided]'}**")
        st.write(f"Consumer email: **{record.user_email or '[not provided]'}**")
        st.write(f"Subject: **{record.subject or 'Consumer complaint'}**")
        st.text_area("Complaint text used for drafting", value=record.display_text(), height=260, disabled=True)

    # Routing instructions are also config-driven.
    jurisdiction_hint = cfg_get(
        "Routing",
        "jurisdiction_hint",
        "Florida / Orlando / MCO if transaction occurred there; otherwise infer from complaint",
    )
    extra_instruction = cfg_get(
        "Routing",
        "extra_instruction",
        (
            "Recommend BBB, state Attorney General, local State Attorney/consumer fraud path, FTC, "
            "credit-card dispute, and company escalation when relevant. Keep criminal language cautious: suspected fraud/deceptive practice."
        ),
    )
    use_openai = cfg_get("Routing", "use_openai", "true").lower() not in ("0", "false", "no", "off")

    with st.expander("Routing settings loaded from config.ini", expanded=False):
        st.write(f"Use OpenAI: `{use_openai}`")
        st.write(f"Jurisdiction hint: {jurisdiction_hint}")
        st.write(extra_instruction)

    st.subheader("2) Generate organization list and letters")
    if st.button("Generate letters using configured settings", type="primary"):
        try:
            if use_openai:
                drafts = generate_outreach_drafts_with_openai(
                    record=record,
                    registry=st.session_state.registry,
                    jurisdiction_hint=jurisdiction_hint,
                    extra_instruction=extra_instruction,
                )
            else:
                drafts = fallback_rule_based_drafts(record, st.session_state.registry)
            st.session_state.drafts = [asdict(d) for d in drafts]
            st.success(f"Generated {len(drafts)} draft(s). Review before sending.")
        except Exception as e:
            st.error(str(e))

    st.subheader("3) Review recipients and letters")
    if not st.session_state.drafts:
        st.info("Generate drafts first.")
        return

    attachments = load_attachment_files_for_record(record)
    if attachments:
        st.success(f"Loaded {len(attachments)} evidence attachment(s) automatically.")
        with st.expander("Evidence attachments", expanded=False):
            for name, data in attachments:
                st.write(f"- {name} ({len(data):,} bytes)")
    else:
        st.info("No evidence attachments were loaded from complaint docs or config.ini.")

    edited_drafts: List[OutreachDraft] = []
    allowed_channels = ["email_if_verified", "web_form", "web_form_or_email_if_verified", "secure_message_or_mail", "manual"]

    for i, d in enumerate(st.session_state.drafts):
        draft = OutreachDraft(**d)
        with st.expander(f"{i+1}. {draft.org_name} - {draft.recommended_channel}", expanded=i == 0):
            include = st.checkbox("Include", value=draft.include, key=f"inc_{i}")
            org_name = st.text_input("Organization", value=draft.org_name, key=f"org_{i}")
            email = st.text_input(
                "Recipient email - leave blank for web form/manual only",
                value=draft.email,
                key=f"email_{i}",
                help="Verify official recipient email before sending. BBB and many agencies generally require web forms.",
            )
            web_url = st.text_input("Web form URL", value=draft.web_url, key=f"web_{i}")
            channel = st.selectbox(
                "Channel",
                allowed_channels,
                index=allowed_channels.index(draft.recommended_channel) if draft.recommended_channel in allowed_channels else 0,
                key=f"channel_{i}",
            )
            st.caption(draft.why_this_org)
            if draft.caution:
                st.warning(draft.caution)
            subject = st.text_input("Subject", value=draft.subject, key=f"subj_{i}")
            body = st.text_area("Letter body", value=draft.body, height=300, key=f"body_{i}")
            edited_drafts.append(
                OutreachDraft(
                    include=include,
                    org_key=draft.org_key,
                    org_name=org_name,
                    category=draft.category,
                    recommended_channel=channel,
                    email=email.strip(),
                    web_url=web_url.strip(),
                    why_this_org=draft.why_this_org,
                    subject=subject,
                    body=body,
                    caution=draft.caution,
                )
            )
            if web_url:
                st.markdown(f"Web form: {web_url}")

    st.divider()
    st.subheader("4) Send selected emails")
    email_ready = [d for d in edited_drafts if d.include and d.email]
    web_only = [d for d in edited_drafts if d.include and not d.email]
    st.write(f"Email-ready drafts: **{len(email_ready)}**")
    st.write(f"Web/manual drafts with no email: **{len(web_only)}**")
    if web_only:
        st.info("For web/manual items, copy the letter body into the official form. They will not be emailed without a recipient address.")

    confirm = st.checkbox(
        "I verified all recipient email addresses and authorize sending the selected emails from my Gmail account.",
        value=False,
    )
    if st.button("Send selected email drafts through Gmail", type="primary", disabled=not confirm):
        if not email_ready:
            st.warning("No selected drafts have recipient email addresses.")
        else:
            sent = 0
            failures = 0
            for draft in email_ready:
                try:
                    result = gmail_send_with_reauth(draft.email, draft.subject, draft.body, attachments=attachments)
                    msg_id = result.get("id", "")
                    log_outreach(st.session_state.loaded_db_path, record.complaint_id, draft, "sent", gmail_message_id=msg_id)
                    sent += 1
                    st.success(f"Sent to {draft.org_name} <{draft.email}>. Gmail message id: {msg_id}")
                except Exception as e:
                    failures += 1
                    hint = ""
                    if is_invalid_grant_error(e):
                        hint = " Reconnect Gmail: the saved refresh token was revoked/expired. Delete cw_gmail_tokens.sqlite/gmail_token.json/token.pickle or rerun the OAuth server, then send again."
                    log_outreach(st.session_state.loaded_db_path, record.complaint_id, draft, "failed", error=str(e))
                    st.error(f"Failed sending to {draft.org_name}: {e}{hint}")
            if sent > 0:
                status_updated = update_native_complaint_module_status(
                    st.session_state.loaded_db_path,
                    record.complaint_id,
                    "escalated_to_authorities",
                    note=f"Regulatory/authority outreach sent to {sent} organization(s); failures={failures}.",
                    meta={"sent": sent, "failures": failures},
                )
                if status_updated:
                    st.success("Complaint Warrior status updated: escalated to authorities.")
            st.info(f"Done. Sent={sent}, failed={failures}.")

    st.subheader("5) Copy/paste package for web forms")
    package = []
    for d in edited_drafts:
        if not d.include:
            continue
        package.append(
            f"### {d.org_name}\nChannel: {d.recommended_channel}\nURL: {d.web_url or '[none]'}\nSubject: {d.subject}\n\n{d.body}\n"
        )
    st.download_button(
        "Download all letters as Markdown",
        data="\n\n---\n\n".join(package).encode("utf-8"),
        file_name=f"complaint_outreach_{record.complaint_id}.md",
        mime="text/markdown",
    )

    if web_only and st.button("Mark selected web/manual submissions as completed"):
        status_updated = update_native_complaint_module_status(
            st.session_state.loaded_db_path,
            record.complaint_id,
            "escalated_to_authorities",
            note=f"User marked {len(web_only)} web/manual regulatory submission(s) as completed.",
            meta={"web_manual_count": len(web_only)},
        )
        if status_updated:
            st.success("Complaint Warrior status updated: escalated to authorities.")
        else:
            st.warning("Could not update the native Complaint Warrior status. The outreach package is still available for download.")


if __name__ == "__main__":
    main()
